export const defaultCopy = {
  home_1: ' EXPERIENCIAS PRIVADAS · MENDOZA, ARGENTINA',
  home_2: 'Hay lugares que se visitan.',
  home_3: 'Y otros que ',
  home_4: 'se sienten.',
  home_5: 'Vinos extraordinarios. Mesas que reúnen. Paisajes que te cambian.',
  home_6: ' Descubrí Mendoza de la mano de quienes la vivimos.',
  home_7: 'Diseñá tu experiencia ',
  home_8: 'Explorá nuestros viajes ',
  home_9: ' 32°53′ S · 68°50′ O ',
  home_10: ' AL PIE DE LOS ANDES',
  home_11: 'UN LUGAR, MIL HISTORIAS ',
  home_12: 'EL VINO ES SOLO EL COMIENZO',
  home_13: ' Bodegas elegidas con criterio',
  home_14: ' Gastronomía con identidad',
  home_15: ' Viajes privados, a tu ritmo',
  home_16: ' Mirada y conocimiento local',
  home_17: 'NUESTRA ESENCIA',
  home_18: 'No hacemos tours.',
  home_19: 'Creamos ',
  home_20: 'conexiones.',
  home_21:
    'Creemos que el verdadero lujo es sentirte parte de un lugar. Conocer a quienes hacen el vino, compartir una mesa sin mirar el reloj y descubrir esa Mendoza que no aparece en las guías.',
  home_22: 'Por eso, cada viaje empieza con una conversación y se diseña alrededor de vos.',
  home_23: 'Conocé nuestra manera de viajar ',
  home_24: 'UNA TIERRA, DISTINTAS EXPRESIONES',
  home_25: 'Tres regiones. ',
  home_26: 'Infinitas historias.',
  home_27: 'Encontrá tu lugar en el mundo del vino.',
  home_28: 'Una cordillera como escenario. Un terroir distinto en cada copa.',
  home_29: 'CURADAS POR NOSOTROS, VIVIDAS POR VOS',
  home_30: 'El arte de ',
  home_31: 'disfrutar Mendoza.',
  home_32: 'Prefiero armar mi viaje ',
  home_33: 'Qué incluye esta experiencia',
  home_34: ' Degustaciones',
  home_35: ' Maridaje',
  home_36: ' Privado',
  home_37: 'DESDE',
  home_38: '/ persona',
  home_39: 'USD · base 2 pasajeros',
  home_40:
    'Precios de referencia en USD, sujetos a disponibilidad y confirmación. Cada experiencia se puede personalizar.',
  home_41: 'MENOS PRISA. MÁS MENDOZA.',
  home_42: 'TU VIAJE, TU PROPIA EXPRESIÓN',
  home_43: 'La mejor experiencia',
  home_44: 'es la que lleva ',
  home_45: 'tu nombre.',
  home_46:
    'Elegí tus días, descubrí bodegas en nuestro mapa y combiná los sabores que más te inspiran. Nosotros nos ocupamos de unir cada detalle.',
  home_47: '01',
  home_48: ' Contanos cuándo y con quién',
  home_49: '02',
  home_50: ' Elegí las bodegas que te inspiran',
  home_51: '03',
  home_52: ' Recibí una propuesta a tu medida',
  home_53: 'Empezá a diseñar tu viaje ',
  home_54: 'Sin compromiso. Con acompañamiento real.',
  home_55: 'ANFITRIONES, ANTES QUE GUÍAS',
  home_56: 'De acá. ',
  home_57: 'Para vos.',
  home_58:
    'Una mirada local que conecta el vino, la cocina y el paisaje. Nuestra propuesta reúne curaduría enológica, coordinación de viajes y acompañamiento personal, desde la primera charla hasta la última copa.',
  home_59: ' Curaduría enológica',
  home_60: ' Sabores del territorio',
  home_61: ' Coordinación local',
  home_62: 'Imágenes de inspiración. Las visitas y los menús se coordinan para cada viaje.',
  home_63: 'LOS BUENOS VIAJES EMPIEZAN CON UNA CHARLA',
  home_64: 'Tu próxima gran historia',
  home_65: 'se escribe ',
  home_66: 'en Mendoza.',
  home_67: 'Hagámosla realidad ',
  header_68: 'terroir',
  header_69: 'MENDOZA · ARGENTINA',
  header_70: 'Nuestra esencia',
  header_71: 'Las regiones',
  header_72: 'Experiencias',
  header_73: 'Diseñá tu viaje',
  header_74: 'Diseñá tu viaje ',
  footer_76: 'terroir',
  footer_77: 'MENDOZA · ARGENTINA',
  footer_78: 'Viajes con origen.',
  footer_79: 'Recuerdos que se quedan.',
  footer_80: 'TU PRÓXIMA HISTORIA',
  footer_81: 'Empieza en Mendoza ',
  footer_82: 'Hecho con el espíritu de nuestra tierra.',
  footer_83: 'Acceso de agencia',
};
