export const defaultCopy = {
  home_1: ' EXPERIENCIAS PRIVADAS · MENDOZA',
  home_2: 'Hay lugares que se visitan.',
  home_3: 'Y otros que ',
  home_4: 'se sienten.',
  home_5: 'Vinos, mesas y paisajes que no se olvidan.',
  home_6: ' Mendoza, de la mano de quienes la vivimos.',
  home_7: 'Diseñá tu experiencia ',
  home_8: 'Explorá nuestros viajes ',
  home_13: ' Bodegas elegidas',
  home_14: ' Cocina con identidad',
  home_15: ' Privado y a tu ritmo',
  home_16: ' Mirada local',
  home_17: 'NUESTRA ESENCIA',
  home_18: 'No hacemos tours.',
  home_19: 'Creamos ',
  home_20: 'conexiones.',
  home_21:
    'El verdadero lujo es sentirte parte del lugar: conocer a quien hace el vino y compartir una mesa sin apuro.',
  home_22: 'Cada viaje empieza con una charla y se diseña alrededor tuyo.',
  home_23: 'Conocé nuestra manera de viajar ',
  home_24: 'UNA TIERRA, DISTINTAS EXPRESIONES',
  home_25: 'Tres regiones. ',
  home_26: 'Infinitas historias.',
  home_27: 'Encontrá tu lugar en el mundo del vino.',
  home_28: 'Un terroir distinto en cada copa.',
  home_29: 'CURADAS POR NOSOTROS',
  home_30: 'El arte de ',
  home_31: 'disfrutar Mendoza.',
  home_32: 'Prefiero armar mi viaje ',
  home_33: 'Qué incluye esta experiencia',
  home_34: ' Degustaciones',
  home_35: ' Maridaje',
  home_36: ' Privado',
  home_37: 'DESDE',
  home_38: '/ persona',
  home_39: 'USD · base 2 pasajeros',
  home_40: 'Cada experiencia se personaliza a tu medida.',
  home_42: 'TU VIAJE, TU PROPIA EXPRESIÓN',
  home_43: 'La mejor experiencia',
  home_44: 'es la que lleva ',
  home_45: 'tu nombre.',
  home_46: 'Elegí tus días y tus bodegas. Nosotros unimos cada detalle.',
  home_47: '01',
  home_48: ' Contanos cuándo y con quién',
  home_49: '02',
  home_50: ' Elegí tus bodegas',
  home_51: '03',
  home_52: ' Recibí tu propuesta',
  home_53: 'Empezá a diseñar tu viaje ',
  home_54: 'Sin compromiso. Con acompañamiento real.',
  home_55: 'ANFITRIONES, ANTES QUE GUÍAS',
  home_56: 'De acá. ',
  home_57: 'Para vos.',
  home_58:
    'Curaduría de vino, cocina y paisaje. Te acompañamos desde la primera charla hasta la última copa.',
  home_59: ' Curaduría enológica',
  home_60: ' Sabores del territorio',
  home_61: ' Coordinación local',
  home_62: 'Imágenes de inspiración. Cada viaje se coordina a medida.',
  home_63: 'EMPECEMOS CON UNA CHARLA',
  home_64: 'Tu próxima gran historia',
  home_65: 'se escribe ',
  home_66: 'en Mendoza.',
  home_67: 'Hagámosla realidad ',
  header_68: 'terroir',
  header_69: 'MENDOZA · ARGENTINA',
  header_70: 'Nuestra esencia',
  header_71: 'Las regiones',
  header_72: 'Experiencias',
  header_73: 'Diseñá tu viaje',
  header_74: 'Diseñá tu viaje ',
  footer_76: 'terroir',
  footer_77: 'MENDOZA · ARGENTINA',
  footer_78: 'Viajes con origen.',
  footer_79: 'Recuerdos que se quedan.',
  footer_80: 'TU PRÓXIMA HISTORIA',
  footer_81: 'Empieza en Mendoza ',
  footer_82: 'Hecho con el espíritu de nuestra tierra.',
  footer_83: 'Acceso de agencia',
};
